<?php require_once __DIR__ . '/components/render.php'; ?>
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
        <?php brasasol_render_seo(); ?>
        <title>Conoce BRASASOL | Cilindros asadores</title>
        <meta name="description" content="Conoce BRASASOL, la marca de cilindros asadores creada por CCP Metal Welding EIRL en Tacna, Perú.">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="icon" type="image/png" href="img/logo/brasasol-favicon.png">
<link rel="stylesheet" href="estilos/styles.css?v=brasasol-ux-v73-20260714">
    </head>
    <body class="bg-black text-white standard-page">
        <?php cargar_componente('topbar'); ?><?php cargar_componente('navbar'); ?>
        <main>
            <section class="page-hero"><div class="container page-hero-grid"><div><span class="product-kicker">Marca peruana de CCP Metal Welding EIRL</span><h1>BRASASOL: cocinar con fuego, técnica y tradición</h1><p>BRASASOL convierte la experiencia metalmecánica en cilindros asadores resistentes y prácticos, diseñados para cocinar carnes y pollo mediante calor indirecto y convección.</p><div class="page-hero-actions"><a href="productos.php" class="btn btn-warning btn-lg rounded-pill"><i class="bi bi-fire me-2"></i>Conocer los cilindros</a><a href="manual.php" class="btn btn-outline-light btn-lg rounded-pill">Ver manual de uso</a></div></div><div class="page-hero-media"><img src="<?= htmlspecialchars(brasasol_site_image('hero_brasasol','img/horno/promos/promo-familiar-destacada.png'), ENT_QUOTES, 'UTF-8') ?>" alt="Cilindro asador BRASASOL con sus accesorios"></div></div></section>
            <section class="py-5 section-dark"><div class="container split-info-grid"><div><span class="product-kicker">Nuestra esencia</span><h2 class="section-title">Una marca nacida de la fabricación metalmecánica</h2><p class="text-light-emphasis fs-5">BRASASOL es la línea gastronómica desarrollada y fabricada por CCP Metal Welding EIRL en Tacna. La marca aplica conocimientos de soldadura y fabricación metálica para ofrecer equipos duraderos, funcionales y fáciles de incorporar a reuniones, hogares y emprendimientos.</p></div><div class="info-list"><div class="info-list-item"><i class="bi bi-wind"></i><div><h3>Cocción vertical</h3><p>El cilindro cocina principalmente con calor indirecto y circulación por convección.</p></div></div><div class="info-list-item"><i class="bi bi-fire"></i><div><h3>Carbón vegetal</h3><p>Trabaja con brasas estables y sin llama directa para lograr una cocción uniforme.</p></div></div><div class="info-list-item"><i class="bi bi-shield-check"></i><div><h3>Fabricación resistente</h3><p>Componentes metálicos pensados para uso frecuente, mantenimiento sencillo y larga duración.</p></div></div></div></div></section>
            <section class="py-5 bg-black"><div class="container"><div class="page-section-head"><span class="product-kicker">Experiencia BRASASOL</span><h2 class="section-title">Más que un cilindro asador</h2><p>Una forma práctica de compartir buena comida alrededor del fuego.</p></div><div class="content-card-grid"><article class="content-card dark"><div class="content-card-body"><h3>Preparaciones versátiles</h3><p>Permite preparar pollo entero o en piezas, cerdo, res y otras carnes utilizando ganchos o parrilla interna.</p></div></article><article class="content-card dark"><div class="content-card-body"><h3>Control del proceso</h3><p>El precalentamiento, las brasas sin llama, la tapa cerrada y la temperatura controlada ayudan a conservar calor, humedad y sabor.</p></div></article><article class="content-card dark"><div class="content-card-body"><h3>Acompañamiento directo</h3><p>El equipo orienta al cliente en la elección de capacidad, accesorios, uso inicial y coordinación de la compra.</p></div></article></div></div></section>
            <section class="py-5 section-dark"><div class="container"><div class="page-section-head"><span class="product-kicker">Diseñado para durar</span><h2 class="section-title">Calidad, seguridad y cuidado</h2></div><div class="account-action-grid"><div class="account-action"><i class="bi bi-thermometer-half"></i><div><h3>Operación controlada</h3><p>Temperatura estimada de 180 °C a 250 °C y precalentamiento aproximado de 15 a 20 minutos.</p></div></div><div class="account-action"><i class="bi bi-hand-index-thumb"></i><div><h3>Uso responsable</h3><p>Superficie estable, guantes térmicos y distancia de materiales inflamables durante la operación.</p></div></div><div class="account-action"><i class="bi bi-droplet-half"></i><div><h3>Mantenimiento sencillo</h3><p>Retirar cenizas y grasa después de cada uso, inspeccionar componentes y secar completamente.</p></div></div></div><div class="text-center mt-4"><a href="nosotros.php" class="btn btn-outline-warning btn-lg rounded-pill">Conocer a CCP Metal Welding EIRL</a></div></div></section>
        </main>
        <?php cargar_componente('footer'); ?><?php cargar_componente('cookies'); ?>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>
