<?php require_once __DIR__ . '/components/render.php'; ?>
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
        <?php brasasol_render_seo(); ?>
        <title>CCP Metal Welding EIRL | Empresa fundadora de BRASASOL</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="icon" type="image/png" href="img/logo/brasasol-favicon.png">
<link rel="stylesheet" href="estilos/styles.css?v=brasasol-ux-v73-20260714">
    </head>
    <body class="bg-black text-white standard-page about-page">
        <?php cargar_componente('topbar'); ?><?php cargar_componente('navbar'); ?>
        <main>
            <section class="page-hero page-hero-nosotros"><div class="container page-hero-grid"><div><span class="product-kicker">Empresa fundadora de BRASASOL</span><h1>CCP Metal Welding EIRL</h1><p>Empresa metalmecánica de Tacna dedicada a desarrollar soluciones especializadas en soldadura, fabricación de productos metálicos, ingeniería y formación técnica.</p><div class="page-hero-actions"><a href="contacto.php" class="btn btn-warning btn-lg rounded-pill"><i class="bi bi-building me-2"></i>Contactar a la empresa</a><a href="brasasol.php" class="btn btn-outline-light btn-lg rounded-pill">Conocer BRASASOL</a></div></div><div class="page-hero-media"><img src="<?= htmlspecialchars(brasasol_site_image('hero_about','img/logo/brasasol-logo.png'), ENT_QUOTES, 'UTF-8') ?>" alt="BRASASOL, marca fundada por CCP Metal Welding EIRL"></div></div></section>
            <section class="py-5 section-dark"><div class="container split-info-grid"><div><span class="product-kicker">Nuestra trayectoria</span><h2 class="section-title">De la experiencia en soldadura a productos que resuelven</h2><p class="text-light-emphasis fs-5">CCP Metal Welding EIRL desarrolla su actividad desde el conocimiento técnico de la fabricación metálica. Esa experiencia dio origen a BRASASOL, su marca de cilindros asadores para el sector gastronómico.</p><p class="text-light-emphasis">La empresa combina fabricación, ingeniería, consultoría y capacitación para atender necesidades domésticas, gastronómicas, estructurales e industriales desde la región sur del Perú.</p></div><div class="info-list"><div class="info-list-item"><i class="bi bi-geo-alt"></i><div><h3>Origen en Tacna</h3><p>La operación y fabricación se desarrollan en Tacna, con atención directa y vocación de crecimiento hacia todo el Perú.</p></div></div><div class="info-list-item"><i class="bi bi-award"></i><div><h3>Conocimiento especializado</h3><p>El trabajo se apoya en personal competente y estándares técnicos aplicables a fabricación, seguridad y soldadura.</p></div></div><div class="info-list-item"><i class="bi bi-lightbulb"></i><div><h3>Innovación aplicada</h3><p>Cada solución busca convertir la experiencia metalmecánica en productos funcionales, resistentes y útiles.</p></div></div></div></div></section>
            <section class="py-5 bg-black"><div class="container"><div class="page-section-head"><span class="product-kicker">Propósito empresarial</span><h2 class="section-title">Misión y visión</h2></div><div class="content-card-grid"><article class="content-card dark"><div class="content-card-body"><i class="bi bi-bullseye fs-2 text-warning"></i><h3 class="mt-3">Misión</h3><p>Satisfacer las necesidades del mercado mediante soluciones especializadas en soldadura, fabricación de productos metálicos, entrenamiento y calificación de soldadores, con altos estándares de calidad, personal competente y un entorno de desarrollo para sus colaboradores.</p></div></article><article class="content-card dark"><div class="content-card-body"><i class="bi bi-eye fs-2 text-warning"></i><h3 class="mt-3">Visión</h3><p>Ser una empresa líder en soluciones industriales, fabricación y capacitación en soldadura, con calidad y seguridad alineadas con estándares nacionales e internacionales, impulsando el crecimiento industrial de la región sur y del Perú.</p></div></article></div></div></section>
            <section class="py-5 section-dark"><div class="container"><div class="page-section-head"><span class="product-kicker">Capacidades</span><h2 class="section-title">Productos y servicios</h2><p>La actividad de CCP Metal Welding EIRL va más allá de una sola línea de productos.</p></div><div class="account-action-grid"><div class="account-action"><i class="bi bi-fire"></i><div><h3>Soluciones gastronómicas</h3><p>Fabricación de cilindros asadores BRASASOL y otros productos metálicos para uso gastronómico.</p></div></div><div class="account-action"><i class="bi bi-building-gear"></i><div><h3>Fabricación e ingeniería</h3><p>Termas solares, techos aligerados, muebles metálicos, casas modulares, casas contenedor y soluciones para maquinaria agrícola.</p></div></div><div class="account-action"><i class="bi bi-person-workspace"></i><div><h3>Formación en soldadura</h3><p>Capacitación, entrenamiento y calificación de soldadores bajo estándares AWS D1.1, API 1104 y ASME Sección IX.</p></div></div><div class="account-action"><i class="bi bi-clipboard2-check"></i><div><h3>Consultoría técnica</h3><p>Actividades de arquitectura, ingeniería y asesoría técnica vinculadas con soluciones metálicas e industriales.</p></div></div></div></div></section>
        </main>
        <?php cargar_componente('footer'); ?><?php cargar_componente('cookies'); ?>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>
